# site properties and page defaults
title: Machine Intelligence in Neuroimaging
subtitle: 
description: MINI @ Weill Cornell Medicine
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: qiz4006@med.cornell.edu
  orcid: 0000-0002-6368-0889
  google-scholar: yHpHM34AAAAJ
  github: mini-cornell
  twitter: QingyuZhaoWCM
  linkedin: qingyu-zhao-aa066a87

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
